# NumPy

In [1]:
import numpy as np

### 1-D array

In [2]:
a=np.array([12,20,30,40])

#### Attributes of arrays

In [3]:
a.dtype

dtype('int32')

In [4]:
a.shape

(4,)

In [5]:
a.ndim

1

In [6]:
a.size

4

In [7]:
a[3]

40

In [8]:
a[1]

20

In [9]:
a[0]

12

In [10]:
a[0:2]

array([12, 20])

### Multi dimensional Array

In [11]:
b=np.array([[1,2,3,4,5,6]])

In [12]:
b

array([[1, 2, 3, 4, 5, 6]])

In [14]:
c=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,5,6,2]])

In [15]:
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 5, 6, 2]])

In [16]:
b.shape

(1, 6)

In [17]:
c.shape

(3, 4)

In [18]:
b.ndim

2

In [19]:
c.ndim

2

In [20]:
b[0]

array([1, 2, 3, 4, 5, 6])

In [22]:
c[2]

array([8, 5, 6, 2])

In [23]:
b.size

6

In [29]:
c.size

12

#### First element in first array

In [30]:
c[0][0]

1

In [31]:
c[1][3]

8

In [32]:
c[2][3]

2

In [35]:
c[1][1]

6

#### Change the dtype

In [36]:
c=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,5,6,2]],dtype=float)

In [37]:
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.],
       [8., 5., 6., 2.]])

### Another type of multi-dimensional array

In [25]:
d = np.array([[[[1,2,3,4]]]])

In [26]:
d

array([[[[1, 2, 3, 4]]]])

In [27]:
d.shape

(1, 1, 1, 4)

In [28]:
d.ndim

4

### Creating bigger arrays

In [38]:
a_big=np.array([
    [
        [1,2,3,4],[4,5,6,7],[8,4,3,2]
    ],
    [
        [2,34,4,5],[7,8,32,5],[0,9,1,2]
    ],
    [
        [9,6,0,43],[7,9,24,5],[21,7,4,5]
    ]

],dtype=float)

In [39]:
a_big

array([[[ 1.,  2.,  3.,  4.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  4.,  3.,  2.]],

       [[ 2., 34.,  4.,  5.],
        [ 7.,  8., 32.,  5.],
        [ 0.,  9.,  1.,  2.]],

       [[ 9.,  6.,  0., 43.],
        [ 7.,  9., 24.,  5.],
        [21.,  7.,  4.,  5.]]])

### Filling arrays

In [42]:
a=np.full((3,3,3),8)

In [45]:
a
a.ndim

3

In [46]:
b=np.zeros((4,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
b.ndim

2

In [50]:
c=np.empty((6,5))
c

array([[ 7.45871124e-312,  1.01283457e-321,  0.00000000e+000,
         0.00000000e+000,  1.33511018e-306],
       [ 1.16097020e-028,  1.26087994e-076,  3.17927163e-028,
         1.57009988e-076,  1.04917183e-153],
       [ 5.23081515e-143,  1.18833786e-075,  2.34253625e-056,
         1.68920024e-051,  1.79109569e+160],
       [-1.69336965e-310,  5.49109388e-143,  1.06396443e+224,
         3.96041428e+246,  1.16318408e-028],
       [ 2.57751694e-056,  2.12985429e-052,  9.77019534e+165,
         8.60430245e-043,  1.01848862e+248],
       [ 1.16096643e-028,  9.80058441e+252,  7.50189709e+247,
         1.14484251e+243,  2.59903827e-144]])

In [52]:
d=np.random.random((4,3))
d

array([[0.11071476, 0.71605436, 0.03094464],
       [0.22606841, 0.64329395, 0.17375886],
       [0.51499926, 0.65614894, 0.79720489],
       [0.80332029, 0.79670923, 0.92356099]])

In [53]:
d.ndim

2

In [54]:
b.ndim

2

In [55]:
a.ndim

3

In [56]:
a_arange=np.arange(5,100,20)
a_arange

array([ 5, 25, 45, 65, 85])

In [57]:
b_linspace=np.linspace(2,30,2)
b_linspace

array([ 2., 30.])

In [59]:
c_lin=np.linspace(1,100,10)
c_lin

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [60]:
c_lin.ndim

1

In [62]:
d_lin=np.linspace(0,100,15,dtype=int)
d_lin

array([  0,   7,  14,  21,  28,  35,  42,  50,  57,  64,  71,  78,  85,
        92, 100])

In [64]:
d_lin=np.exp(a)
d_lin

array([[[2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704]],

       [[2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704]],

       [[2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704],
        [2980.95798704, 2980.95798704, 2980.95798704]]])

In [68]:
c=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,5,6,2]],dtype=int)
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 5, 6, 2]])

In [69]:
c=np.exp(c)
c

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [2.98095799e+03, 1.48413159e+02, 4.03428793e+02, 7.38905610e+00]])

In [70]:
c=np.sin(c)
c

array([[ 0.41078129,  0.89385495,  0.94447101, -0.92876794],
       [-0.68769141,  0.96486625, -0.21561571,  0.40176297],
       [ 0.40176297, -0.68769141,  0.96486625,  0.89385495]])

In [72]:
c=np.cos(c)

c

array([[0.91680911, 0.62641178, 0.58617154, 0.59882118],
       [0.77271346, 0.56952682, 0.97684485, 0.92037303],
       [0.92037303, 0.77271346, 0.56952682, 0.62641178]])

In [73]:
c=np.tan(c)
c

array([[1.30460586, 0.7236333 , 0.66402502, 0.68240764],
       [0.97494704, 0.64030118, 1.48083693, 1.31428058],
       [1.31428058, 0.97494704, 0.64030118, 0.7236333 ]])

In [74]:
c=np.log(c)
c

array([[ 0.26590098, -0.32347051, -0.40943545, -0.38212809],
       [-0.02537213, -0.44581663,  0.39260742,  0.27328943],
       [ 0.27328943, -0.02537213, -0.44581663, -0.32347051]])

In [76]:
d=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,5,6,2]],dtype=int)
d

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 5, 6, 2]])

In [77]:
d=np.sqrt(d)
d


array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [2.82842712, 2.23606798, 2.44948974, 1.41421356]])

In [78]:
b=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [8,5,6,2]],dtype=int)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 5, 6, 2]])

In [79]:
b.sum()

57

In [80]:
b.min()

1

In [81]:
b.max()

8

In [82]:
b.mean()

4.75

In [87]:
np.median(b)

5.0

In [88]:
np.std(b)

2.277608394786075